name: Test Project
on: workflow_dispatch
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: './packages.lock.json'
      - name: Install Nuget
      - uses: actions/checkout@master
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'
      - run: nuget restore MyDotNetApp.sln
      - name: comment
        run: echo "Hello world"
      
      # - name: Install dependencies
      #   run: npm ci
      # - name: Run tests
      #   run: npm test
 